trigger:
  branches:
    include: ["master", "v*"]
  paths:
    exclude: ["*.md"]

jobs:
- template: azure-pipelines/build-template.yml
  parameters:
    name: Windows
    poolName: Hosted VS2017

- template: azure-pipelines/build-template.yml
  parameters:
    name: MacOs
    poolName: Hosted macOS


- template: azure-pipelines/build-template.yml
  parameters:
    name: Linux
    poolName: Hosted Ubuntu 1604